config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	root 'tasks#index'

	get 'tasks/index'
	post 'tasks/index'

	get 'tasks/action'
	post 'tasks/action'
	post 'tasks/tasks/action' => 'tasks#action'
	get 'tasks/result'  => 'tasks#result'
	post 'tasks/update' => 'tasks#update'
	get 'tasks/updateflag'  => 'tasks#updateflag'
	post 'tasks/updateflag'  => 'tasks#updateflag'
	get 'tasks/trend'  => 'tasks#trend'

	resources(:tasks)
	
# get    'tasks'     => 'tasks#index'
# get    'tasks/:id' => 'tasks#show'
# get    'tasks/new' => 'tasks#new'
# post   'tasks'     => 'tasks#create'
# get    'tasks/:id/edit' => 'tasks#edit'
# delete 'tasks/:id' => 'tasks#destroy'
# put    'tasks/:id' => 'tasks#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
	has_one :task
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user

# タスク追加（modelとcontrollerのやりとりの練習）
	def self.create(task_params)
		@task = Task.new(task_params)
		if @task.save
			return;
		else
			@tasks = Task.all
		end
	end

# 未実行タスクのランダム選択 + 実施済みフラグを立てる
  def self.taskAct(user_id)
  	  tasks = Task.order("RANDOM()").where(user_id: user_id,created_at: Time.zone.now.all_day, doneflag: false)
      acttask = tasks[0]
      return acttask if acttask.nil? 
      task = Task.find(acttask.id)
      task.doneflag = true
      task.save
      return acttask
  end

# flagによる次のサイクル判定
	def self.nextTaskCheck(user_id,checkflag)
	case 
	      # 長い休憩
	  when 0 == checkflag % 9
	  	return breakLong(user_id,checkflag)
	      # 小休憩
	  when 0 != checkflag % 2
	  	return breakShort(user_id,checkflag)
	      # タスク実行
	  else
	  	return actTimer(user_id,checkflag)
	end
	end


# サイクル判定後の[分,フラグ,次のタスク]の実施値を返す
	def self.actTimer(user_id,checkflag)
		nextflag = 1 + checkflag
		acttask = taskAct(user_id)
		return [25,nextflag,acttask]
	end

	def self.breakShort(user_id,checkflag)
		nextflag = 1 + checkflag
		acttask = Task.new(title: "refresh", detail: "short")
		return [5,nextflag,acttask]
	end

	def self.breakLong(user_id,checkflag)
		nextflag = 1 + checkflag
        acttask = Task.new(title: "refresh", detail: "long")
		return [15,nextflag,acttask]      
	end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tasks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @falsetasks = Task.where(user_id: current_user.id,created_at: Time.zone.now.all_day, doneflag: false)
    @truetasks = Task.where(user_id: current_user.id,created_at: Time.zone.now.all_day, doneflag: true)
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to :action => :index
  end


  # ポモドーロのサイクル（タスク→休憩）
  def action
    if request.get? then  # 1回目の処理はget、2回目からはpost
      @min, @nextflag, @acttask = Task.actTimer(current_user.id, 0)
      redirect_to :action => :index if @acttask.id.nil? 
    else  # 2回目（休憩→タスクのサイクルが続く）
    checkflag = params[:flag].to_i   # checkflagから、休憩かタスクの判定
    @min, @nextflag, @acttask = Task.nextTaskCheck(current_user.id,checkflag)
    redirect_to :action => :result if @acttask.nil? 
    end
  end

  def result
    @tasks = Task.where(user_id: current_user.id,created_at: Time.zone.now.all_day,)
    @task = Task.new
  end

  def updateflag
    update_data = params[:task]
    update_data.each {|key, value|
      unit = Task.where(id: key)
      unless unit  # データがなかった場合、indexへ
        redirect_to :action => :index
      end
      if value == "true"
        unit[0].doneflag = true # フラグを設定
        unit[0].save
      else
        unit[0].doneflag = false # フラグを設定
        unit[0].save
      end
    }
    @tasks = Task.where(user_id: current_user.id,created_at: Time.zone.now.all_day,)
    redirect_to :action => :result
  end

  def trend
    # @chart_data = {}
    # ['日', '月', '火', '水', '木', '金', '土'].each_with_index do |dow, i|
    # # sqlite3は、extractをサポートしていない
    # # count_by_dow = Task.where(["extract(dow from created_at AT TIME ZONE 'UTC' AT TIME ZONE 'JST') = ? and user_id = ?", i,current_user.id]).count
    # count_by_dow = Task.where(["strftime('%w', updated_at) = ? and user_id = ?", i,current_user.id]).count
    # # binding.pry
    # @chart_data.store(dow,count_by_dow)
    # end
    # ---------
    @chart_data = {}
    @dowCountNum = 0
    @userAllTasks = Task.where(user_id: current_user.id)
    # @userAllTasks.updated_at = @userAllTasks.updated_at.strftime('%w')
    ['日', '月', '火', '水', '木', '金', '土'].each_with_index do |dow, i|
    @dowCountNum = 0
      @userAllTasks.each do |task|
        if task.updated_at.strftime('%w').to_i == i
          @dowCountNum = @dowCountNum + 1
          @chart_data.store(dow,@dowCountNum)
        end
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    obj = Task.find(params[:id])
    obj.update(task_params)
    redirect_to :action => :index
  end

  def destroy
    obj = Task.find(params[:id])
    obj.destroy
    redirect_to :action => :index
  end

  private
  def task_params
    params.require(:task).permit(:title, :detail, :user_id)
  end

  def correct_user
    task = Task.find(params[:id])
    if current_user.id != task.user.id
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskPomodoro</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>

<body>
  <!-- header-content -->
  <nav class="container navbar header-color">
    <div class="pc-menu" id="title">
      <a class="navbar-brand">ポモドーロ</a>
      <ul class="nav navbar-nav navbar-right">
        <li><a class="menu-box" href="#favorite_section" title="">ポモドーロとは</a></li>
        <li><%= link_to '実行リスト作成', tasks_index_path %></li>
        <li><%= link_to '結果', tasks_result_path %></li>
        <li><%= link_to '傾向', tasks_trend_path %></li>
        <li></li>
        <% if user_signed_in? %>
        <li><a href="" title="">Logged in as <%= current_user.email %></a></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>





  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/tasks/action.html.erb
<div class="container text-center">
   <table class="table table-hover">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>実施内容</th>
      </tr>
    </thead>
    <tbody>
        <td><%= @acttask.title %></td>
        <td><%= @acttask.detail %></td>
      </tr>
    </tbody>
  </table>


<!-- タイマー -->
<form name="timer">
<input type="text" value="<%= @min %>">分
<input type="text" value="0">秒<br>
<input type="button" value="スタート" onclick="cntStart()">
<input type="button" value="ストップ" onclick="cntStop()">
</form>

<%= form_tag(controller: "tasks",action:"action") do  %>
  <%= hidden_field_tag :flag, @nextflag %>
  <%= submit_tag %>
<% end %>

</div>

<!-- スクリプト -->
<script>

var timer1; //タイマーを格納する変数（タイマーID）の宣言
// var target = document.getElementById("switch");

//カウントダウン関数を1000ミリ秒毎に呼び出す関数
function cntStart()
{
  document.timer.elements[2].disabled=true;
  timer1=setInterval("countDown()",1000);
}

//タイマー停止関数
function cntStop()
{
  document.timer.elements[2].disabled=false;
  clearInterval(timer1);
}

//カウントダウン関数
function countDown()
{
  var min=document.timer.elements[0].value;
  var sec=document.timer.elements[1].value;
  
  if( (min=="") && (sec=="") )
  {
    alert("時刻を設定してください！");
    reSet();
  }
  else
  {
    if (min=="") min=0;
    min=parseInt(min);
    
    if (sec=="") sec=0;
    sec=parseInt(sec);
    
    tmWrite(min*60+sec-1);
  }
}

//残り時間を書き出す関数
function tmWrite(int)
{
  int=parseInt(int);
  
  if (int<=0)
  {
    reSet();
    alert("時間です！");
    document.name.submit();
  }
  else
  {
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[0].value=Math.floor(int/60);
    //残り秒数はintを60で割った余り
    document.timer.elements[1].value=int % 60;
  }
}

//フォームを初期状態に戻す（リセット）関数
function reSet()
{
  document.timer.elements[0].value="0";
  document.timer.elements[1].value="0";
  document.timer.elements[2].disabled=false;
  clearInterval(timer1);
}  
  
</script>

app/views/tasks/edit.html.erb
<h1>Task#edit</h1>
<pre>
	
		<%= form_for(@task, url:{controller:'tasks',action:'update',id:@task.id}) do |form|%>
		<table>
		<tr>
			<th>Title</th>
			<td><%= form.text_field :title %></td>
		</tr>
		<tr>
			<th>detail</th>
			<td><%= form.text_field :detail %></td>
		</tr>
		<tr>
			<th></th>
			<%= form.hidden_field :user_id, value:current_user.id %>
			<td><%= form.submit "送信" %></td>
		</tr>
		</table>
		<% end %>
	
</pre>

app/views/tasks/index.html.erb
<div class="container text-center">
<h1>実行リスト作成</h1>

<%= form_for(@task) do |f| %>
<div class="container-fluid">
<div class="table-responsive">
  <div>タスク名：<%= f.text_field :title %></div>
  <div>実施内容：<%= f.text_field :detail %></div>
  <div><%= f.hidden_field :user_id, value:current_user.id %></div>
  <div><%= f.submit %></div>
  <br>
<% end %>
</div>
<hr>
</div>
</div>

<div class="container">
  <h2 class="page-header ">本日の未実行タスク => <%= link_to '実行', controller: "tasks", action: "action" %></h2>
    <table class="table table-hover">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>実施内容</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      <tr><% @falsetasks.each do |task| %>
        <td><%= task.title %></td>
        <td><%= task.detail %></td>
        <td><%= link_to 'Edit', edit_task_path(task.id) %></td>
        <td><%= link_to 'Destroy', task_path(task.id), :method => :delete %></td>
      </tr><% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <h2 class="page-header orange">本日の実行済みタスク</h2>
    <table class="table table-hover">
    <thead>
      <tr>
        <th class="text-center">タイトル</th>
        <th class="text-center">実施内容</th>
      </tr>
    </thead>
    <tbody>
      <tr><% @truetasks.each do |task| %>
        <td class="text-center"><%= task.title %></td>
        <td class="text-center"><%= task.detail %></td>
      </tr><% end %>
    </tbody>
  </table>
</div>

app/views/tasks/result.html.erb
本日のタスクが実行できたのか確認



<%= form_for @task, :url => {:action => :updateflag } do |f| %>
<%= f.submit "更新" %>
<%= link_to '傾向', tasks_trend_path %>

	<table class="table table-hover">
		<thead>
			<tr >
				<th>title</th>
				<th>detail</th>
				<th>flag</th>
			</tr>
		</thead>
		<tbody>
			<% @tasks.each_with_index{|r, idx| @r = r %>
			<tr>
				<td><%= @r.title %></td>
				<td><%= @r.detail %></td>
				<td><%= f.select @r.id,  ["true","false"], {:selected=>@r.doneflag, :index => idx} %></td>
			</tr>
			<%}%>
		</tbody>
	</table>
<% end %>

app/views/tasks/trend.html.erb
<%= line_chart @chart_data %>
<hr>
<%= line_chart @chart_data2 %>

app/views/tasks/update.html.erb
<% @tasks.each do |task| %>
  <%= task.id %> 
  : <%= task.title %> 
  : <%= task.detail %>
  : <%= task.doneflag %><br>
  <br>
<% end %>
<%= link_to '実行', controller: "tasks", action: "trend" %>